/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BootstrapProvider: typeof import('../components/bootstrap-provider')['BootstrapProvider']
  const ConnectButton: typeof import('../components/connect-button')['ConnectButton']
  const DiscordIcon: typeof import('../components/icons')['DiscordIcon']
  const FormShipping: typeof import('../components/form-shipping')['FormShipping']
  const GithubIcon: typeof import('../components/icons')['GithubIcon']
  const HeartFilledIcon: typeof import('../components/icons')['HeartFilledIcon']
  const InjectsProvider: typeof import('../components/injects-provider')['InjectsProvider']
  const InputPhoneNumber: typeof import('../components/form-shipping')['InputPhoneNumber']
  const Logo: typeof import('../components/icons')['Logo']
  const MenuIcon: typeof import('../components/icons')['MenuIcon']
  const MoonFilledIcon: typeof import('../components/icons')['MoonFilledIcon']
  const OrdersPreview: typeof import('../components/orders-preview')['OrdersPreview']
  const SearchIcon: typeof import('../components/icons')['SearchIcon']
  const SettingIcon: typeof import('../components/icons')['SettingIcon']
  const SettingsDialog: typeof import('../components/settings-dialog')['SettingsDialog']
  const SunFilledIcon: typeof import('../components/icons')['SunFilledIcon']
  const ThemeSwitch: typeof import('../components/theme-switch')['ThemeSwitch']
  const TwitterIcon: typeof import('../components/icons')['TwitterIcon']
  const createRef: typeof import('react')['createRef']
  const findMobilePrefix: typeof import('../components/form-shipping.utils')['findMobilePrefix']
  const forwardRef: typeof import('react')['forwardRef']
  const layouts: typeof import('../layouts/index')['layouts']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const motion: typeof import('framer-motion')['motion']
  const parsePhone: typeof import('../components/form-shipping.utils')['parsePhone']
  const startTransition: typeof import('react')['startTransition']
  const store: typeof import('../store/index')['default']
  const subtitle: typeof import('../components/primitives')['subtitle']
  const title: typeof import('../components/primitives')['title']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRouter: typeof import('next/router')['useRouter']
  const useState: typeof import('react')['useState']
  const useStoreUser: typeof import('../hooks/use-store-user')['useStoreUser']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ConnectButtonProps } from '../components/connect-button'
  import('../components/connect-button')
  // @ts-ignore
  export type { FieldType, InputPhoneNumberProps } from '../components/form-shipping'
  import('../components/form-shipping')
  // @ts-ignore
  export type { SettingsDialogProps } from '../components/settings-dialog'
  import('../components/settings-dialog')
  // @ts-ignore
  export type { ThemeSwitchProps } from '../components/theme-switch'
  import('../components/theme-switch')
}
