/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BootstrapProvider: typeof import('../components/bootstrap-provider')['BootstrapProvider']
  const CarIcon: typeof import('../components/icons')['CarIcon']
  const ConnectButton: typeof import('../components/connect-button')['ConnectButton']
  const DiscordIcon: typeof import('../components/icons')['DiscordIcon']
  const FormShipping: typeof import('../components/form-shipping')['FormShipping']
  const GithubIcon: typeof import('../components/icons')['GithubIcon']
  const HeartFilledIcon: typeof import('../components/icons')['HeartFilledIcon']
  const HomeFloatProjects: typeof import('../ui/home-float-projects')['HomeFloatProjects']
  const HomeFloatProjectsUnline: typeof import('../ui/home-float-projects-unline')['HomeFloatProjectsUnline']
  const InjectsProvider: typeof import('../components/injects-provider')['InjectsProvider']
  const InputPhoneNumber: typeof import('../components/form-shipping')['InputPhoneNumber']
  const Logo: typeof import('../components/icons')['Logo']
  const LsiconScreenFullFilled: typeof import('../components/icons')['LsiconScreenFullFilled']
  const MaterialSymbolsArrowForwardIosRounded: typeof import('../components/icons')['MaterialSymbolsArrowForwardIosRounded']
  const MaterialSymbolsContactSupport: typeof import('../components/icons')['MaterialSymbolsContactSupport']
  const MenuIcon: typeof import('../components/icons')['MenuIcon']
  const MoonFilledIcon: typeof import('../components/icons')['MoonFilledIcon']
  const OrderDetail: typeof import('../components/order-detal')['OrderDetail']
  const OrderPreview: typeof import('../components/order-preview')['OrderPreview']
  const OrderTable: typeof import('../components/order-table')['OrderTable']
  const OrdersPreview: typeof import('../components/orders-preview')['OrdersPreview']
  const ProductDescription: typeof import('../ui/product-description')['ProductDescription']
  const ProductDetailDialog: typeof import('../components/product-detail-dialog')['ProductDetailDialog']
  const ProductForm: typeof import('../ui/product-form')['ProductForm']
  const ProductHeader: typeof import('../ui/product-header')['ProductHeader']
  const ProductImages: typeof import('../ui/product-images')['ProductImages']
  const QuestionIcon: typeof import('../components/icons')['QuestionIcon']
  const ScreenFullIcon: typeof import('../components/icons')['ScreenFullIcon']
  const SearchIcon: typeof import('../components/icons')['SearchIcon']
  const SettingIcon: typeof import('../components/icons')['SettingIcon']
  const SettingsDialog: typeof import('../components/settings-dialog')['SettingsDialog']
  const SunFilledIcon: typeof import('../components/icons')['SunFilledIcon']
  const ThemeSwitch: typeof import('../components/theme-switch')['ThemeSwitch']
  const TwitterIcon: typeof import('../components/icons')['TwitterIcon']
  const baseURL: typeof import('../api/index')['baseURL']
  const clsx: typeof import('clsx')['default']
  const container: typeof import('../components/primitives')['container']
  const createRef: typeof import('react')['createRef']
  const findMobilePrefix: typeof import('../components/form-shipping.utils')['findMobilePrefix']
  const forwardRef: typeof import('react')['forwardRef']
  const getOrder: typeof import('../api/index')['getOrder']
  const getProduct: typeof import('../api/index')['getProduct']
  const getProductFilesSuffix: typeof import('../api/index')['getProductFilesSuffix']
  const getProductId: typeof import('../api/index')['getProductId']
  const getProductIdVariations: typeof import('../api/index')['getProductIdVariations']
  const getProductIdVariationsVariation: typeof import('../api/index')['getProductIdVariationsVariation']
  const getUser: typeof import('../api/index')['getUser']
  const getUserInspect: typeof import('../api/index')['getUserInspect']
  const getUserLogout: typeof import('../api/index')['getUserLogout']
  const getUserNonce: typeof import('../api/index')['getUserNonce']
  const layouts: typeof import('../layouts/index')['layouts']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const motion: typeof import('framer-motion')['motion']
  const parsePhone: typeof import('../components/form-shipping.utils')['parsePhone']
  const postOrder: typeof import('../api/index')['postOrder']
  const postOrderPaid: typeof import('../api/index')['postOrderPaid']
  const postUserVerify: typeof import('../api/index')['postUserVerify']
  const putUser: typeof import('../api/index')['putUser']
  const startTransition: typeof import('react')['startTransition']
  const store: typeof import('../store/index')['default']
  const subtitle: typeof import('../components/primitives')['subtitle']
  const title: typeof import('../components/primitives')['title']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRouter: typeof import('next/router')['useRouter']
  const useState: typeof import('react')['useState']
  const useStoreUser: typeof import('../hooks/use-store-user')['useStoreUser']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ConnectButtonProps } from '../components/connect-button'
  import('../components/connect-button')
  // @ts-ignore
  export type { FormShippingFields, InputPhoneNumberProps } from '../components/form-shipping'
  import('../components/form-shipping')
  // @ts-ignore
  export type { ProductDetailDialogProps } from '../components/product-detail-dialog'
  import('../components/product-detail-dialog')
  // @ts-ignore
  export type { SettingsDialogProps } from '../components/settings-dialog'
  import('../components/settings-dialog')
  // @ts-ignore
  export type { ThemeSwitchProps } from '../components/theme-switch'
  import('../components/theme-switch')
  // @ts-ignore
  export type { ProductDescriptionProps } from '../ui/product-description'
  import('../ui/product-description')
  // @ts-ignore
  export type { ProductFormProps } from '../ui/product-form'
  import('../ui/product-form')
  // @ts-ignore
  export type { ProductImagesProps } from '../ui/product-images'
  import('../ui/product-images')
}
