/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BootstrapProvider: typeof import('../src/components/bootstrap-provider')['BootstrapProvider']
  const CancelConfirmDialog: typeof import('../src/components/cancel-confirm-dialog')['CancelConfirmDialog']
  const CarIcon: typeof import('../src/components/icons')['CarIcon']
  const ConnectButton: typeof import('../src/components/connect-button')['ConnectButton']
  const DeleteConfirmDialog: typeof import('../src/components/delete-confirm-dialog')['DeleteConfirmDialog']
  const Dicebear: typeof import('../src/components/dicebear')['Dicebear']
  const DiscordIcon: typeof import('../src/components/icons')['DiscordIcon']
  const FormShipping: typeof import('../src/components/form-shipping')['FormShipping']
  const GithubIcon: typeof import('../src/components/icons')['GithubIcon']
  const HeartFilledIcon: typeof import('../src/components/icons')['HeartFilledIcon']
  const HomeFloatProjects: typeof import('../src/ui/home-float-projects')['HomeFloatProjects']
  const HomeFloatProjectsUnline: typeof import('../src/ui/home-float-projects-unline')['HomeFloatProjectsUnline']
  const InjectsProvider: typeof import('../src/components/injects-provider')['InjectsProvider']
  const InputPhoneNumber: typeof import('../src/components/form-shipping')['InputPhoneNumber']
  const Lens: typeof import('../src/components/lens')['Lens']
  const Logo: typeof import('../src/components/icons')['Logo']
  const MaterialSymbolsArrowCoolDownRounded: typeof import('../src/components/icons')['MaterialSymbolsArrowCoolDownRounded']
  const MaterialSymbolsArrowForwardIosRounded: typeof import('../src/components/icons')['MaterialSymbolsArrowForwardIosRounded']
  const MaterialSymbolsLightEyeTrackingRounded: typeof import('../src/components/icons')['MaterialSymbolsLightEyeTrackingRounded']
  const MenuIcon: typeof import('../src/components/icons')['MenuIcon']
  const MingcuteWarningFill: typeof import('../src/components/icons')['MingcuteWarningFill']
  const MoonFilledIcon: typeof import('../src/components/icons')['MoonFilledIcon']
  const OrderDetail: typeof import('../src/components/order-detal')['OrderDetail']
  const OrderPreview: typeof import('../src/components/order-preview')['OrderPreview']
  const OrderTable: typeof import('../src/components/order-table')['OrderTable']
  const ProductDescription: typeof import('../src/ui/product-description')['ProductDescription']
  const ProductDetailDialog: typeof import('../src/components/product-detail-dialog')['ProductDetailDialog']
  const ProductForm: typeof import('../src/ui/product-form')['ProductForm']
  const ProductImages: typeof import('../src/ui/product-images')['ProductImages']
  const QuestionIcon: typeof import('../src/components/icons')['QuestionIcon']
  const ScreenFullIcon: typeof import('../src/components/icons')['ScreenFullIcon']
  const SearchIcon: typeof import('../src/components/icons')['SearchIcon']
  const SettingIcon: typeof import('../src/components/icons')['SettingIcon']
  const SettingsDialog: typeof import('../src/components/settings-dialog')['SettingsDialog']
  const SunFilledIcon: typeof import('../src/components/icons')['SunFilledIcon']
  const ThemeSwitch: typeof import('../src/components/theme-switch')['ThemeSwitch']
  const TwitterIcon: typeof import('../src/components/icons')['TwitterIcon']
  const addresses: typeof import('../src/generated/index')['addresses']
  const baseURL: typeof import('../src/apis/index')['baseURL']
  const bidirectionalTransferAbi: typeof import('../src/generated/index')['bidirectionalTransferAbi']
  const chain: typeof import('../src/generated/index')['chain']
  const chains: typeof import('../src/generated/index')['chains']
  const client: typeof import('../src/generated/index')['client']
  const clipboardCopy: typeof import('../src/utils/clipboardCopy')['clipboardCopy']
  const clsx: typeof import('clsx')['default']
  const container: typeof import('../src/components/primitives')['container']
  const createRef: typeof import('react')['createRef']
  const deleteOrderId: typeof import('../src/apis/index')['deleteOrderId']
  const detail: typeof import('../src/components/order-detail.mock')['detail']
  const erc1967ProxyAbi: typeof import('../src/generated/index')['erc1967ProxyAbi']
  const erc20Abi: typeof import('../src/generated/index')['erc20Abi']
  const erc6551AccountAbi: typeof import('../src/generated/index')['erc6551AccountAbi']
  const erc6551RegistryAbi: typeof import('../src/generated/index')['erc6551RegistryAbi']
  const findMobilePrefix: typeof import('../src/components/form-shipping.utils')['findMobilePrefix']
  const formatDate: typeof import('../src/utils/formatDate')['formatDate']
  const forwardRef: typeof import('react')['forwardRef']
  const getBidirectionalTransfer: typeof import('../src/generated/index')['getBidirectionalTransfer']
  const getContract: typeof import('../src/generated/index')['getContract']
  const getErc1967Proxy: typeof import('../src/generated/index')['getErc1967Proxy']
  const getErc20: typeof import('../src/generated/index')['getErc20']
  const getErc6551Account: typeof import('../src/generated/index')['getErc6551Account']
  const getErc6551Registry: typeof import('../src/generated/index')['getErc6551Registry']
  const getIerc6551Account: typeof import('../src/generated/index')['getIerc6551Account']
  const getIerc6551AccountProxy: typeof import('../src/generated/index')['getIerc6551AccountProxy']
  const getIerc6551Registry: typeof import('../src/generated/index')['getIerc6551Registry']
  const getIhoFueltank: typeof import('../src/generated/index')['getIhoFueltank']
  const getIhoLockVaultV1: typeof import('../src/generated/index')['getIhoLockVaultV1']
  const getIhoLockVaultV2: typeof import('../src/generated/index')['getIhoLockVaultV2']
  const getIhoMarket: typeof import('../src/generated/index')['getIhoMarket']
  const getIhoMining: typeof import('../src/generated/index')['getIhoMining']
  const getIihoFuel: typeof import('../src/generated/index')['getIihoFuel']
  const getOrder: typeof import('../src/apis/index')['getOrder']
  const getOrderId: typeof import('../src/apis/index')['getOrderId']
  const getProduct: typeof import('../src/apis/index')['getProduct']
  const getProductId: typeof import('../src/apis/index')['getProductId']
  const getProductIdStatistics: typeof import('../src/apis/index')['getProductIdStatistics']
  const getProductIdVariations: typeof import('../src/apis/index')['getProductIdVariations']
  const getProductIdVariationsVariation: typeof import('../src/apis/index')['getProductIdVariationsVariation']
  const getProductStatistics: typeof import('../src/apis/index')['getProductStatistics']
  const getProductStatisticsId: typeof import('../src/apis/index')['getProductStatisticsId']
  const getStats: typeof import('../src/apis/index')['getStats']
  const getUser: typeof import('../src/apis/index')['getUser']
  const getUserInspect: typeof import('../src/apis/index')['getUserInspect']
  const getUserLogout: typeof import('../src/apis/index')['getUserLogout']
  const getUserNonce: typeof import('../src/apis/index')['getUserNonce']
  const getVerifiableUpgradeable: typeof import('../src/generated/index')['getVerifiableUpgradeable']
  const ierc6551AccountAbi: typeof import('../src/generated/index')['ierc6551AccountAbi']
  const ierc6551AccountProxyAbi: typeof import('../src/generated/index')['ierc6551AccountProxyAbi']
  const ierc6551RegistryAbi: typeof import('../src/generated/index')['ierc6551RegistryAbi']
  const ihoFueltankAbi: typeof import('../src/generated/index')['ihoFueltankAbi']
  const ihoLockVaultV1Abi: typeof import('../src/generated/index')['ihoLockVaultV1Abi']
  const ihoLockVaultV2Abi: typeof import('../src/generated/index')['ihoLockVaultV2Abi']
  const ihoMarketAbi: typeof import('../src/generated/index')['ihoMarketAbi']
  const ihoMiningAbi: typeof import('../src/generated/index')['ihoMiningAbi']
  const iihoFuelAbi: typeof import('../src/generated/index')['iihoFuelAbi']
  const layouts: typeof import('../src/layouts/index')['layouts']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const motion: typeof import('framer-motion')['motion']
  const orderDetailMock: typeof import('../src/components/order-detail.mock')['orderDetailMock']
  const parseOrderTracking: typeof import('../src/components/order.utils')['parseOrderTracking']
  const parsePhone: typeof import('../src/components/form-shipping.utils')['parsePhone']
  const postOrder: typeof import('../src/apis/index')['postOrder']
  const postOrderPay: typeof import('../src/apis/index')['postOrderPay']
  const postUserVerify: typeof import('../src/apis/index')['postUserVerify']
  const putOrderCancel: typeof import('../src/apis/index')['putOrderCancel']
  const putUser: typeof import('../src/apis/index')['putUser']
  const removeInnerHTMLAttributes: typeof import('../src/utils/removeInnerHTMLAttributes')['removeInnerHTMLAttributes']
  const startTransition: typeof import('react')['startTransition']
  const store: typeof import('../src/store/index')['default']
  const subtitle: typeof import('../src/components/primitives')['subtitle']
  const title: typeof import('../src/components/primitives')['title']
  const transactionConfirmedToast: typeof import('../src/utils/transactionConfirmedToast')['transactionConfirmedToast']
  const transactionWaitingReceipt: typeof import('../src/utils/transactionWaitingReceipt')['transactionWaitingReceipt']
  const useAsyncCallbacks: typeof import('../src/hooks/use-async-callbacks')['useAsyncCallbacks']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRouter: typeof import('next/router')['useRouter']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
  const verifiableUpgradeableAbi: typeof import('../src/generated/index')['verifiableUpgradeableAbi']
  const verifyInsufficientFunds: typeof import('../src/utils/verifyInsufficientFunds')['verifyInsufficientFunds']
  const wallet: typeof import('../src/generated/index')['wallet']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ConnectButtonProps } from '../src/components/connect-button'
  import('../src/components/connect-button')
  // @ts-ignore
  export type { DicebearProps } from '../src/components/dicebear'
  import('../src/components/dicebear')
  // @ts-ignore
  export type { FormShippingFields, InputPhoneNumberProps } from '../src/components/form-shipping'
  import('../src/components/form-shipping')
  // @ts-ignore
  export type { LensProps } from '../src/components/lens'
  import('../src/components/lens')
  // @ts-ignore
  export type { OrderDetailProps } from '../src/components/order-detal'
  import('../src/components/order-detal')
  // @ts-ignore
  export type { OrderTableProps } from '../src/components/order-table'
  import('../src/components/order-table')
  // @ts-ignore
  export type { ProductDetailDialogProps } from '../src/components/product-detail-dialog'
  import('../src/components/product-detail-dialog')
  // @ts-ignore
  export type { SettingsDialogProps } from '../src/components/settings-dialog'
  import('../src/components/settings-dialog')
  // @ts-ignore
  export type { ThemeSwitchProps } from '../src/components/theme-switch'
  import('../src/components/theme-switch')
  // @ts-ignore
  export type { ProductDescriptionProps } from '../src/ui/product-description'
  import('../src/ui/product-description')
  // @ts-ignore
  export type { ProductFormProps } from '../src/ui/product-form'
  import('../src/ui/product-form')
  // @ts-ignore
  export type { ProductImagesProps } from '../src/ui/product-images'
  import('../src/ui/product-images')
}
