import { wagmiConfig } from '@/config'
import { SubscribeWagmiConfig } from '@/generated'
import { Injector, useFetchResponseIntercept } from '@hairy/react-lib'
import { addToast, ToastProvider } from '@heroui/react'
import { OverlaysProvider } from '@overlastic/react'
import { RainbowKitProvider } from '@rainbow-me/rainbowkit'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import Head from 'next/head'
import { useMount } from 'react-use'
import { WagmiProvider } from 'wagmi'
import '@/styles/globals.css'
import '@rainbow-me/rainbowkit/styles.css'
import { jsonTryParse } from '@hairy/utils'

export default function App({ Component, pageProps }: any) {
  const client = new QueryClient()
  useMount(() => {
    if (process.env.NEXT_PUBLIC_NETWORK === 'moonchain_geneva')
      Reflect.get(window, 'eruda')?.init()
  })

  useFetchResponseIntercept(async (response, init) => {
    const text = await response.clone().text()
    const data = jsonTryParse(text)
    if (data?.statusCode) {
      if (data.error && !Reflect.get(init || {}, 'skipMessage'))
        addToast({ color: 'danger', description: data.message })
      throw data
    }

    if (!data)
      return response
    const value = JSON.stringify(data)
    return new Response(value, response)
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Injector
        install={[
          { component: WagmiProvider, props: { config: wagmiConfig } },
          { component: QueryClientProvider, props: { client } },
          { component: RainbowKitProvider },
          { component: OverlaysProvider },
        ]}
      >
        <ToastProvider placement="top-center" />
        <Component {...pageProps} />
        <SubscribeWagmiConfig />
      </Injector>
    </>
  )
}
