import { wagmiConfig } from '@/config'
import { Injector } from '@hairy/react-lib'
import { OverlaysProvider } from '@overlastic/react'
import { RainbowKitProvider } from '@rainbow-me/rainbowkit'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

import Head from 'next/head'
import { useMount } from 'react-use'
import { WagmiProvider } from 'wagmi'
import '@/styles/globals.css'
import '@rainbow-me/rainbowkit/styles.css'

export default function App({ Component, pageProps }: any) {
  const client = new QueryClient()

  useMount(() => {
    if (process.env.NEXT_PUBLIC_NETWORK === 'moonchain_geneva')
      Reflect.get(window, 'eruda')?.init()
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Injector
        install={[
          { component: WagmiProvider, props: { config: wagmiConfig } },
          { component: QueryClientProvider, props: { client } },
          { component: RainbowKitProvider },
          { component: OverlaysProvider },
        ]}
      >
        <Component {...pageProps} />
        <SubscribeWagmiConfig />
      </Injector>
    </>
  )
}
